# Install scripts. (runs after repo cloning)
install:
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
  # install modules
  - npm install

cache:
 - C:\projects\ts-minecraft\node_modules

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version

build_script:
  - npm run build

artifacts:
  - path: dist/index.js
    name: ts-minecraft

on_success:
  - ps: if ($env:APPVEYOR_REPO_BRANCH -eq "main") {C:\projects\ts-minecraft\build_scripts\discord-webhook.ps1 success $env:DISCORD_WEBHOOK_URL}
on_failure:
  - ps: if ($env:APPVEYOR_REPO_BRANCH -eq "main") {C:\projects\ts-minecraft\build_scripts\discord-webhook.ps1 failure $env:DISCORD_WEBHOOK_URL}
